### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#263] opened 2022-09-29 14:23 UTC
Sondehub crash for several days = websocket error

**Comment by darksidelemm** [comment] 2022-09-29 21:18
Without any further details (like what error is showing up in the javascript console) I can't help with this.

**Comment by 14ri004** [comment] 2022-10-02 14:05
We are several people in the same situation, blocking the update of probehub, forced to restart the software several times, error websocket = 0 msg
this problem appeared 15-20 days ago, thanks

**Comment by darksidelemm** [comment] 2022-10-02 22:23
Sorry, still not sure what the issue is. I've had it running fine here.
Make sure you clear your browser cache in case you are using an out-dated version of the web interface.

When the issue happens again, I would suggest looking at the Browser Console, or Javascript console of your web browser for any errors.

**Comment by 14ri004** [comment] 2022-10-03 10:35
whether on 8 PCs and 4 Android phones, we have the same problems, during the reception of SondeHub it blocks in error, and we no longer receive the data from the probe, it is mandatory to close the window and restart (https:// testing.v2.sondehub.org)

emptying the cache does not change anything, same problem with several probe hunters, Chrome or Firefox, this problem did not exist less than a month ago

**Comment by darksidelemm** [comment] 2022-10-03 10:37
After how long is this happening? Again, If you encounter an issue, I need you to open up your browsers web or javascript console and look for any errors there.

Also, please use https://tracker.sondehub.org/ - which is the 'stable' version of the tracker.

**Comment by 14ri004** [comment] 2022-10-03 10:45
it does it very often, sometimes it works and sometimes it doesn't, totally random, I'll try https://tracker.sondehub.org/ and see what happens, thanks

![error](https://user-images.githubusercontent.com/87615097/193559107-7b4460e9-0a1f-4661-85f1-53ff6d521754.PNG)

**Comment by darksidelemm** [comment] 2022-10-03 10:57
Got a possible idea on what might be happening. Surprised its breaking the tracker completely mind you, i would expect it would still continue to update (though it might show error in the bottom right).

**Comment by darksidelemm** [comment] 2022-10-03 11:02
A potential fix has been deployed, relating to what ends up in what websocket topic. This may or may not solve the issue.

**Comment by 14ri004** [comment] 2022-10-03 11:10
I'm testing the https://tracker.sondehub.org version, and I'll see if it changes anything, I'll let you know if it solves our problem, thank you

**Comment by darksidelemm** [comment] 2022-10-03 11:11
This particular fix will apply to both (I think...), since the problem is 'upstream' of the tracker website itself (though may have broken something in the tracker).

**Comment by 14ri004** [comment] 2022-10-03 11:20
I haven't had any websocket errors for 10 minutes, it seems to work perfectly as before, on my Android phone it was crashing every 30 seconds, and for the moment no more errors, it's perfect, congratulations, nice work, thank you

**Comment by 14ri004** [comment] 2022-10-03 13:27
after more than an hour without worries, data error is displayed on the screen, blocking of reception of data from the probe for 2 to 3 minutes, we are 4 people to have noticed the same problem, it seems to me due to the quantity of data or the number of probes in the air to be treated??

![error2](https://user-images.githubusercontent.com/87615097/193589116-20c59685-46ff-4c0e-a778-9a7bca77e4b6.PNG)

**Comment by 14ri004** [comment] 2022-10-03 13:39
4 minutes blocked, data error while the probe is still decoded at the time of the screenshot

![error3](https://user-images.githubusercontent.com/87615097/193591715-4737d656-46b6-4591-8e33-d079ed01aae7.PNG)

**Comment by 14ri004** [comment] 2022-10-04 06:20
hello, small precision, the problem only occurs when there are many probes in flight, but if there are only 2 or 3 probes in flight there are no errors, this problem is identical with 4 other friends and at the same time, we are using TTGOs with RDZsonde, and this problem appeared only very recently, thanks

**Comment by darksidelemm** [comment] 2022-10-04 07:01
The second error can be dis-regarded, the .map files are unimportant.

The first ones  (Websockets Error) are the new debug statements i've added which show the age of the packet which tripped the error. This doesn't necessarily mean things are broken, just that that batch of packets (the number of packets indicated by 'frame length') have been discarded. 

There are a few more changes that can be made, but I'm wondering if this is simply your web browser not keeping up.

**Comment by 14ri004** [comment] 2022-10-04 07:08
it does it for me on 3 pc and 1 android phone, and I have 4 other friends for whom the problem is the same and at the same time, when it crashes it does it for us 5, I use W10 pro and updated Firefox , 24mb VDSL connection, and TTGO + rdz

**Comment by darksidelemm** [comment] 2022-10-04 07:14
What you are using for tracking is not important here. This issue is about data coming from sondehub.

I still haven't really clarified from you what exactly 'crashing' means. Sure, there might be a websocket error in the console, but that just means it's discarding some packets. You are saying that it stops updating, then recovers and continues on? This does sound like your browser is not keeping up.

Can you please try out the site using another browser, e.g. Google Chrome or Chromium?

**Comment by 14ri004** [comment] 2022-10-04 07:15
![Uploading error5.PNG…]()

**Comment by darksidelemm** [comment] 2022-10-04 07:19
Does the web-socket indication keep updating at this point? Does the msg/s indication update?
It should update fairly regularly with different times in the brackets. 

Do any other sondes continue to update?

**Comment by 14ri004** [comment] 2022-10-04 07:22
yes the websocket is changing, currently not many probes in flight,

**Comment by darksidelemm** [comment] 2022-10-04 07:25
OK, I want you to confirm the following:
- You are seeing a *specific* sonde stop updating.
- When the error occurs (and presumably immediately disappears), other radiosonde continue to update.

This is sounding like it is in fact NOT an issue with the tracker (however we have made some valuable changes in the process), but is in fact just data from a particular sonde not being updated.

I'm watching that sonde too (DFM09, 18066063) and I haven't seen any telemetry updates for a while now, which suggests either the sonde is not transmitting, or there is some other issue going on with telemetry submission, either way, not an issue with the tracker website itself.

**Comment by 14ri004** [comment] 2022-10-04 07:29
yes indeed the probe no longer transmits it seems, but before cutting there was indeed the concern of slowing down the data received from probehub, I install chrome to see if the problem continues or not

**Comment by darksidelemm** [comment] 2022-10-04 07:33
Please continue to test using https://testing.v2.sondehub.org/ 

I've made further changes that will result in the number next to websockets indication going negative occasionally (this is expected). What I'm looking for is issues where your browser window *completely* stops updating. This means:
- No updates to the number next to the websockets indication (this should update with every new message from the server).
- No position updates on *any* radiosondes, not just a specific radiosonde.
- The websockets indication being replaced with 'data error' and staying like that (if this occurs I would suggest opening the developer tools console and looking for any errors (Which should be in *red*).

Hopefully we can nail down if there is actually an issue, and if so, where it is.

**Comment by 14ri004** [comment] 2022-10-04 07:39
I decode the RS41 T3630973 under chrome, the websocket indicates negative seconds, the number of msg/s changes, for the moment no problems with decoding or data blocking on probehub

**Comment by 14ri004** [comment] 2022-10-04 08:15
![Capture](https://user-images.githubusercontent.com/87615097/193769200-f17fbc59-181d-4c83-b3c3-56e74e273205.PNG)

**Comment by darksidelemm** [comment] 2022-10-04 08:19
You can ignore that, that's indicating it couldn't get some map tiles.

**Comment by 14ri004** [comment] 2022-10-04 12:31
Lots of data errors, stuck updating tracking info on probehub, 2-3min refresh, test with chrome, firefox and edge, test on RS41-M10-M20-DFM9, and it seems to come when a large amount of data is received, it is not due to my station since exactly the same problem with 4 other friends distant from 50 to 250 km,

![error8](https://user-images.githubusercontent.com/87615097/193819800-a136a9d6-9bdf-4b46-bfc6-f14b5505285e.PNG)
![error10](https://user-images.githubusercontent.com/87615097/193819836-98f76536-830a-488d-8421-fbfd4a1d6e40.PNG)

**Comment by darksidelemm** [comment] 2022-10-04 21:42
As per my previous comment on this issue, can you confirm that in this state:

- There are no updates to the number next to the websockets indication (this should update with every new message from the server).
- There are no position updates on *any* radiosondes, not just a specific radiosonde.

If the websockets indication *is* locking up (and in your examples they are showing different things), then could you please have a look in the developer tools console for any errors shown at that time.

**Comment by darksidelemm** [comment] 2022-10-04 21:48
I have made one more change in testing.v2.sondehub.org that stops the page performing a complete refresh if the data age is > 150 seconds, which may have been causing the issues.

**Comment by 14ri004** [comment] 2022-10-05 04:07
hello, the msg/s figure changes when it does a complete update of the probe data (altitude, gps, etc.) but remains blocked when error data is displayed, it can be 1mn or 5mn, during this time the probe this moves but on probehub it remains blocked, and this unlocks for 1 or 2 minutes and the screen freezes, I have 2 other people who have exactly the same problem as us, which makes 7 people with the same problems receiving probehub

**Comment by darksidelemm** [comment] 2022-10-05 07:31
OK, a few more things then:
- Can you describe what you are running this on. You said Windows computer and android phones - what specifications? CPU, RAM, etc.
- Your web browser should have a 'task manager' function, which shows you RAM and CPU usage of each tab. I would like to know what's going on with that when this occurs.

I'm still thinking there is just too much data coming through for your browser to handle.

**Comment by 14ri004** [comment] 2022-10-05 08:22
I myself tested on 3 PCs (Core 2 duo, i3, i5), RAM from 4 to 16 GB, DD SSD, VDSL 24Mb, Samsung S7 Android phone

and my friends use i5 or i7 PCs with 16 and 32 GB
Chrome, Firefox, and Edge, Adsl or Fiber, Apple Phone.

actually 1 person can have a problem with his PC, but 7 people with totally different configurations, and having the same Symptoms at the same time and totally impossible, there must be other people in the same case as us.
and for 1 month the problem has appeared for everyone, but only during the big release of probes at 1:00 p.m.
thank you mark

**Comment by darksidelemm** [comment] 2022-10-05 08:31
Sure, and this is most likely just a result of the high amount of data being passed through sondehub with all the new stations. This is not an easy problem to solve. If we limit the amount of data going through the system, then we get complains about packets being missed. If we try and add filtering by location, then stations have to download even more data if they pan to somewhere else. If we do other kinds of packet de-duplication, then our server CPU usage skyrockets.

I fully expect a system running only 4GB of RAM and a Core 2 Duo to not keep up with this site. A Samsung S7 is likely also going to have issues due to limited RAM and CPU.

Earlier on I asked you to look and see if there are any errors in the javascript console when the lockups occur. Please do this and get back to me, as it will give me more information if there is some other error occurring. If there are no errors shown, then it is likely the browser tab not keeping up. Please continue to use testing.v2.sondehub.org (you will probably need to clear your cache again), as this has further changes which may help things.

Another test for you is when you start getting lockups, try and filter the page to just one radiosonde. You can do this by putting the sonde sonde serial number in the box at the top left. If this stops the lockups, then it's definitely a too-much-data issue.

**Comment by 14ri004** [comment] 2022-10-05 08:51
indeed you are probably right about the too much data received, we are going to do 2 groups this afternoon, normal reception and reception on 1 probe, and see the result at the end of the day, which confirms that in the morning when 2 or 3 probes fly in France, the reception is perfect, but after 1:00 p.m. a lot of probes fly = slowdown

I'll let you know the outcome,

**Comment by 14ri004** [comment] 2022-10-05 08:52
Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». testing.v2.sondehub.org
Un accès partitionné à un cookie ou au stockage a été fourni à « https://xc5dqkj2cgb1.statuspage.io/embed/frame » car il est chargé dans le contexte tiers et le partitionnement d’état dynamique est activé.
Content Security Policy: « 'unsafe-inline' » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Content Security Policy: « https: » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Content Security Policy: « http: » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Content Security Policy: « 'unsafe-inline' » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Content Security Policy: « https: » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Content Security Policy: « http: » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
WebSockets Error: Data Age was 146.8 s, frame length: 9 mobile.js:8:129285
MouseEvent.mozPressure est obsolète. Veuillez utiliser plutôt PointerEvent.pressure. leaflet.js:5:261
La mémoire consommée par will-change est trop importante. La limite du budget correspond à la surface multipliée par 3 (828160 px). Les occurrences de will-change dépassant le budget seront ignorées. testing.v2.sondehub.org
WebSockets Error: Data Age was 49.9 s, frame length: 11 mobile.js:8:129285
WebSockets Error: Data Age was 147.6 s, frame length: 111 mobile.js:8:129285
Erreur dans les liens source : Error: request failed with status 403
URL de la ressource : https://testing.v2.sondehub.org/js/leaflet.js
URL du lien source : leaflet.js.map
WebSockets Error: Data Age was 148.1 s, frame length: 121 mobile.js:8:129285
WebSockets Error: Data Age was 63.1 s, frame length: 11 mobile.js:8:129285
WebSockets Error: Data Age was 63.2 s, frame length: 16 mobile.js:8:129285
WebSockets Error: Data Age was 158.3 s, frame length: 93 mobile.js:8:129285
WebSockets Error: Data Age was 147.7 s, frame length: 99 mobile.js:8:129285
WebSockets Error: Data Age was 153.6 s, frame length: 1 mobile.js:8:129285
WebSockets Error: Data Age was 148.3 s, frame length: 117 mobile.js:8:129285
WebSockets Error: Data Age was 148.3 s, frame length: 160 mobile.js:8:129285
WebSockets Error: Data Age was 51.7 s, frame length: 6 mobile.js:8:129285
WebSockets Error: Data Age was 203.8 s, frame length: 117 mobile.js:8:129285
WebSockets Error: Data Age was 64.2 s, frame length: 15 mobile.js:8:129285
WebSockets Error: Data Age was 147.2 s, frame length: 85 mobile.js:8:129285
WebSockets Error: Data Age was 147.5 s, frame length: 20 mobile.js:8:129285
WebSockets Error: Data Age was 266.2 s, frame length: 26 mobile.js:8:129285
WebSockets Error: Data Age was 147.0 s, frame length: 15 mobile.js:8:129285
WebSockets Error: Data Age was 154.1 s, frame length: 153 mobile.js:8:129285
WebSockets Error: Data Age was 60.8 s, frame length: 2 mobile.js:8:129285
Content Security Policy: « 'unsafe-inline' » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Content Security Policy: « https: » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Content Security Policy: « http: » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Content Security Policy: « 'unsafe-inline' » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Content Security Policy: « https: » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Content Security Policy: « http: » ignoré à l’intérieur de script-src : l’attribut « strict-dynamic » est spécifié
Erreur dans les liens source : Error: request failed with status 403
URL de la ressource : https://testing.v2.sondehub.org/js/leaflet.js
URL du lien source : leaflet.js.map

**Comment by 14ri004** [comment] 2022-10-05 09:21
Is it not possible to limit the amount of data sent by the TTGOs, Example 1 frame every 10s, which could limit the slowdowns, given the large number of stations decoding at 1:00 p.m., or another solution, limit the probes within a radius of 1000km (configurable) around the station (green dot) and thus only see the probes which concern us, the USA/Australia probes, Japan etc. I never look at them, this would limit the amount of data to be sent by the server to the stations, when do you

**Comment by darksidelemm** [comment] 2022-10-05 09:28
Limiting data based on radius is not practical - this requires per-client filtering on the server side, which uses too much CPU.

Limiting data uploaded from particular receiver stations only slows down the problem, it doesn't completely solve it - remember there are > 800 users uploading data to sondehub at the moment

I am looking into other performance speedup possibility on the tracker, but there's always going to be some minimum system performance requirement for it to work reliably.

**Comment by darksidelemm** [comment] 2022-10-05 11:01
We have made some further updates that may improve performance. Please clear cache and test. If you hit lockups, please have a look in the Console for websockets debug information.

**Comment by 14ri004** [comment] 2022-10-05 12:20
WORST than yesterday, 4 minutes stuck on the same position, I emptied the firefox cache, I put the number of one (1) probe in the follow-up and the problem is still present, for 4 friends it is exactly the same, reception blocked, frozen, error data, no sensor update for 3 to 4 minutes

![error14](https://user-images.githubusercontent.com/87615097/194058747-5a8735cb-f2cd-4a88-a373-46ec560a847a.PNG)
![error15](https://user-images.githubusercontent.com/87615097/194058782-30dc13eb-78d4-46b6-aeb5-d0c42af7510c.PNG)
![error16](https://user-images.githubusercontent.com/87615097/194058797-9166fc9b-bdb3-4a83-a8f0-1fe5738be01f.PNG)

**Comment by darksidelemm** [comment] 2022-10-05 21:07
OK, so this does help figure out some of the issues. It's not a performance issue, but a data issue. 

I had a look at the data from the sonde you filtered to - those data age checks should have only resulted in a data age of ~17 seconds (and this is only because rdz_ttgo_sonde is 'slow feeding' the data to us, instead of sending it in a batch). However your system is reporting a data age > 60 seconds. This means your system clock is out. 

First - **Please check your system clock is set correctly.** Windows is terrible at doing this accurately, so you may need to use some other utility. If your system clock is out, then the checks on data age will fail, and data will be discarded.

I'm now going to increase the data age limit to 100 seconds. I do not necessarily want to make this change permanent, but i am interested to see how it affects things on your end.

**Comment by 14ri004** [comment] 2022-10-06 03:53
Hello mark, we posted a message on a Facebook on radiosondes, and we found other people who also noticed big slowdowns in the reception of data from probehub, this affects a lot of people more or less important, in the morning with 10 probes in flight it works wonderfully, but in the afternoon around 2:30 p.m. it becomes a disaster, I hope you find the solution to this problem, probehub is really excellent for tracking probes, and you have made a very good job, thank you

**Comment by TheSkorm** [comment] 2022-10-06 06:43
I'm really confused. When filtering on a single sonde we only send the data for that single sonde - which means less things to draw on your map. Fundamentally this functionality hasn't changed in the 30 days or so.
![image](https://user-images.githubusercontent.com/234867/194231942-f48981b7-19cd-4934-aa4a-f0d2d0ba7ea3.png)

We can see that this is correctly working.

**Comment by darksidelemm** [comment] 2022-10-06 06:55
I have just made the following changes to the testing branch ( https://testing.v2.sondehub.org/ again, you will need to clear your cache to get this. )
- We no longer check the age of any data arriving via websockets. We just process it anyway. There will be no more 'data error' messages. Either it will be getting data, or it wont. 
- We now use a [page lifecycle 'resume' event](https://developer.chrome.com/blog/page-lifecycle-api/) to trigger a polled refresh if the page has been suspended.

There is not much we can do about the page slowing down during peak times. The changes we made last night did result in a 50% speedup, at least in our testing, however we cannot do much if your machine is already slow.

**Comment by 14ri004** [comment] 2022-10-06 06:57
hello michaela, yes I have no doubt that on your continent it works well, but with us it becomes very difficult to follow a probe during the big release of probes at 1:00 p.m., after 1 hour of flight slowdowns, data errors, frozen page , this unblocks from time to time for a few seconds for a random update, and reblocks and freezes the page, this appeared about 1 month ago, and worse and worse, currently I have 8 people with the same concerns, and surely others to come in the next few days, thank you

**Comment by 14ri004** [comment] 2022-10-06 07:06
ok mark, I'm going to do the tests in the afternoon after 2:00 p.m. (France) and I'll let you know what happens next, for my laptop the problem is identical on my 2 other PCs i3 and my i5, the result is the same on the 3 pc, and my friends are in the same case with i5 or i7 PCs, so it is likely that it comes from the core2 duo 2000Mhz pc, since it received probehub perfectly 1 month ago

**Comment by darksidelemm** [comment] 2022-10-06 07:23
When you are doing this test, open the browsers 'task manager'. This will show the CPU usage, and more importantly the memory usage of your browser tabs.
<img width="498" alt="Screen Shot 2022-10-06 at 17 52 15" src="https://user-images.githubusercontent.com/1040275/194243252-abe327d4-bfb8-4118-8414-712911f9949c.png">


It is expected for the memory usage of the SondeHub tracker page to increase quite significantly during peak sonde time. If you run out of RAM then the page will likely lock up. This is just a result of the amount of data going through the system.

**Comment by 14ri004** [comment] 2022-10-06 07:28
ok mark, I just cleared the firefox cache, and I'm going to check the memory and cpu

**Comment by darksidelemm** [comment] 2022-10-06 09:55
Yet more changes made to try and speed things up further...

**Comment by TheSkorm** [comment] 2022-10-06 12:13
Testing version:
![image](https://user-images.githubusercontent.com/234867/194308775-5fea959d-a0ea-4cc8-b26e-b79fb0d8d31e.png)

Prod version:
![image](https://user-images.githubusercontent.com/234867/194308807-cf087bd1-09d8-4728-b68b-f0e9ba021338.png)

CPU usage about 20% lower than prod as well according to task manager.

I was able to kind of replicate the data error issue on prod by using 1 core 4GB machine running in a VM then having the tab suspended - waiting for a large number of messages to buffer and then unsuspending the tab. On unsuspend it tried to catch up but never did.
![Screen Shot 2022-10-06 at 10 48 07 pm](https://user-images.githubusercontent.com/234867/194309125-ae24884b-e3f4-4f60-870f-2f1cf834b021.png)
![Screen Shot 2022-10-06 at 10 37 35 pm](https://user-images.githubusercontent.com/234867/194309183-8cad6e3c-4213-4f24-b71e-31b9dd466216.png)


These are probably the last set of changes we can make to SondeHub Tracker to improve performance without doing a full rewrite of how the objects are loaded (which none of the team have time to do).

**Comment by 14ri004** [comment] 2022-10-06 12:50
it worked very well between 1:00 p.m. and 2:30 p.m., perfect reception, smooth, and fast updating, but from 2:30 p.m. misery, websocket 30 msg/s, random updating, page frozen for 1 to 2 minutes, data arrives in jerks every 1mn see more, I have the same problem on my i5, and with other people exactly the same and at the same time, I checked the firefox task manager and the pc seems to be running correctly, practically identical on my i5, I do not understand what is happening, it is always around the same time that the reception problems appear

![Capture2](https://user-images.githubusercontent.com/87615097/194317064-922c7d9e-b8ca-4107-b396-acdac58455ee.PNG)

**Comment by 14ri004** [comment] 2022-10-06 13:09
strangely around 3:00 p.m. everything works fine again, normal decoding, correct update, websocket 30 msg/s, no more random blocking, for the moment it's perfect

**Comment by TheSkorm** [comment] 2022-10-06 20:40
This issue looks like it caused by our MQTT read instances (what the tracker connects to) being overwhelmed and running out of CPU credits.
![image](https://user-images.githubusercontent.com/234867/194412213-3d78cd43-99de-4505-9b8c-3d5b2ca2c2be.png). When it runs out of credits it appears to de dropping connections, or pausing packet delivery to certain clients.
![image](https://user-images.githubusercontent.com/234867/194414110-b5c117e8-fea3-45aa-95ff-9196f35fac9f.png)

Since there are multiple servers if the websockets disconnect or drop it might connect to another instance which is working (until that server is overwhelmed)

At around 12:50 UTC I doubled the number of servers and this will hopefully fix the issue. This however comes at a cost so please make sure y'all are signed up on [Patreon](http://patreon.com/sondehub) or monthly [PayPal](http://sondehub.org/go/donate) donations.

I think this has fixed the issue, however it's hard for me to test as the issue only occurs at midnight our time and we need to work in the morning :)

@darksidelemm I still think its worth rolling out the UI speed improvements - those have certainly improved the speed of the UI in a benchmark-able and demonstrable way. This will drop support for any clients that didn't have websocket support - but I think this is ok

**Comment by 14ri004** [comment] 2022-10-08 10:28
hello, indeed for 2 days the system has been working perfectly again, no more slowdowns, perfect data updating, no more blockages or frozen pages, we are back like 1 month ago, good job, good weekend, thank you.

**Closed** 2022-10-08 21:27 UTC
