### ISSUE TITLE
SkewT Plots sometimes hang

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#290] opened 2023-07-07 01:47 UTC
SkewT plots sometimes hang and don't generate. 
Seems to be related to having lots of data on-ground prior to launch. Test using YPAD launches, which are received on-ground.

**Comment by TheSkorm** [comment] 2024-11-20 01:02
Duplicate of #272 probably

**Closed by TheSkorm** 2024-11-20 01:02 UTC
